IF(PlusLib_DIR OR PlusApp_DIR)
  FIND_PACKAGE(PlusLib REQUIRED NO_MODULE PATHS ${PlusLib_DIR} PATH_SUFFIX src)
  FIND_PACKAGE(PlusApp REQUIRED NO_MODULE PATHS ${PlusApp_DIR})

  MESSAGE(STATUS "Using PlusLib available at: ${PlusLib_DIR}")
  MESSAGE(STATUS "Using PlusApp available at: ${PlusApp_DIR}")
  
  SET(RobartsVTK_PlusLib_BIN_DIR ${PlusLib_DIR})
  SET(RobartsVTK_PlusApp_BIN_DIR ${PlusApp_DIR})
ELSE()
  MESSAGE(STATUS "Downloading and building Plus from: https://subversion.assembla.com/svn/plus/trunk/PlusBuild")

  IF( WIN32 )
    SET(USE_WIN32_DEVICE ON)
  ELSE()
    SET(USE_WIN32_DEVICE OFF)
  ENDIF()

  SET (PLUS_SRC_DIR ${ep_dependency_DIR}/Plus CACHE INTERNAL "Path to store PlusBuild contents.")
  SET (PLUS_BIN_DIR ${ep_dependency_DIR}/Plus-bin CACHE INTERNAL "Path to store PlusBuild contents.")
  ExternalProject_Add(Plus
    PREFIX "${ep_dependency_DIR}/Plus-prefix"
    SOURCE_DIR "${PLUS_SRC_DIR}"
    BINARY_DIR "${PLUS_BIN_DIR}"
    #--Download step--------------
    SVN_USERNAME ${PLUS_ASSEMBLA_USERNAME}
    SVN_PASSWORD ${PLUS_ASSEMBLA_PASSWORD}
    SVN_REPOSITORY https://subversion.assembla.com/svn/plus/trunk/PlusBuild
    #--Configure step-------------
    CMAKE_ARGS 
      ${ep_common_args}
      -DVTK_DIR:PATH=${RobartsVTK_VTK_DIR}
      -DITK_DIR:PATH=${RobartsVTK_ITK_DIR}
      ${OpenCV_Dependency_Arg}
      -DBUILD_TESTING:BOOL=OFF
      -DPLUSBUILD_DOWNLOAD_PlusDATA:BOOL=OFF 
      -DBUILD_SHARED_LIBS:BOOL=ON
      -DPLUSBUILD_BUILD_PLUSAPP:BOOL=${RobartsVTK_BUILD_APPS}
      -DQT_QMAKE_EXECUTABLE:FILEPATH=${QT_QMAKE_EXECUTABLE}
      -DPLUSBUILD_VTK_RENDERING_BACKEND:STRING=OpenGL2
      -DQt5_DIR:PATH=${Qt5_DIR}
      -DCMAKE_CXX_FLAGS:STRING=${ep_common_cxx_flags}
      -DCMAKE_C_FLAGS:STRING=${ep_common_c_flags}    
      -DPLUSBUILD_USE_OpenIGTLink:BOOL=ON
      -DPLUS_USE_tesseract:BOOL=ON
      -DPLUS_USE_ULTRASONIX_VIDEO:BOOL=OFF
      -DPLUS_USE_BKPROFOCUS_VIDEO:BOOL=OFF
      -DPLUS_USE_BKPROFOCUS_CAMERALINK:BOOL=OFF
      -DPLUS_USE_ICCAPTURING_VIDEO:BOOL=OFF
      -DPLUS_USE_CAPISTRANO_VIDEO:BOOL=OFF
      -DPLUS_USE_INTERSON_VIDEO:BOOL=OFF
      -DPLUS_USE_INTERSONSDKCXX_VIDEO:BOOL=OFF
      -DPLUS_USE_TELEMED_VIDEO:BOOL=OFF
      -DPLUS_USE_THORLABS_VIDEO:BOOL=OFF
      -DPLUS_USE_VFW_VIDEO:BOOL=${USE_WIN32_DEVICE}
      -DPLUS_USE_EPIPHAN:BOOL=${USE_WIN32_DEVICE}
      -DPLUS_USE_NDI:BOOL=${RobartsVTK_BUILD_APPS}
      -DPLUS_USE_NDI_CERTUS:BOOL=OFF
      -DPLUS_USE_MICRONTRACKER:BOOL=OFF
      -DPLUS_USE_OPTIMET_CONOPROBE:BOOL=OFF
      -DPLUS_USE_OPTITRACK:BOOL=OFF
      -DPLUS_USE_IntuitiveDaVinci:BOOL=OFF
      -DPLUS_USE_BRACHY_TRACKER:BOOL=OFF
      -DPLUS_USE_Ascension3DG:BOOL=OFF
      -DPLUS_USE_Ascension3DGm:BOOL=OFF
      -DPLUS_USE_PHIDGET_SPATIAL_TRACKER:BOOL=OFF
      -DPLUS_USE_3dConnexion_TRACKER:BOOL=OFF
      -DPLUS_USE_MMF_VIDEO:BOOL=${USE_WIN32_DEVICE}
      -DPLUS_USE_STEALTHLINK:BOOL=OFF
      -DPLUS_USE_PHILIPS_3D_ULTRASOUND:BOOL=OFF
      -DBUILD_DOCUMENTATION:BOOL=OFF
    #--Install step-----------------
    INSTALL_COMMAND "" # Do not install
    DEPENDS ${Plus_DEPENDENCIES}
    )
    
  SET(RobartsVTK_PlusLib_BIN_DIR ${PLUS_BIN_DIR}/PlusLib-bin)
  SET(RobartsVTK_PlusApp_BIN_DIR ${PLUS_BIN_DIR}/PlusApp-bin)
ENDIF()